### PR TITLE
1

### PR DESCRIPTION
**Pull request by ahmadm70**
Check my code

### CODE REVIEW

**Review by UlviNovruzov — APPROVED** [review]
All is great, go on!!!

**Review by feyruz-loopcamp — CHANGES_REQUESTED** [review]
Can you change the day format to be October 07. 2023

**Comment by ahmadm70** [comment]
It has been changed

**Review by feyruz-loopcamp — APPROVED** [review]
Thank you. Looks good

**Review by UlviNovruzov — APPROVED** [review]

**Pull request merged**
